# Generated by Django 6.0.4 on 2026-05-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ORGANIZATION', 'Organization'), ('BRANCH_ADMIN', 'Branch Admin'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], max_length=20, verbose_name='Role'),
        ),
    ]
