# Generated by Django 6.0.4 on 2026-05-24 00:00

import uuid
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalLoginToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("token_hash", models.CharField(max_length=64, verbose_name="Token Hash")),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Used At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="approval_login_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Login Token",
                "verbose_name_plural": "Approval Login Tokens",
            },
        ),
    ]
