volumes:
  core_local_postgres_data: {}
  core_local_postgres_data_backups: {}
  core_local_redis_data: {}
  core_local_minio_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: core_local_django
    container_name: core_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: core_production_postgres
    container_name: core_local_postgres
    volumes:
      - core_local_postgres_data:/var/lib/postgresql/18/docker
      - core_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  adminer:
    image: adminer
    container_name: core_local_adminer
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: core_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:8.0
    container_name: core_local_redis
    volumes:
      - core_local_redis_data:/data

  celeryworker:
    <<: *django
    image: core_local_celeryworker
    container_name: core_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: core_local_celerybeat
    container_name: core_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: core_local_flower
    container_name: core_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: core_local_minio
    env_file:
      - ./.envs/.local/.django
    ports:
      - ${S3_PORT}:9000
      - ${S3_CONSOLE_PORT}:${S3_CONSOLE_PORT}
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    volumes:
      - core_local_minio_data:/data
    command: server /data --console-address ":${S3_CONSOLE_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  mc:
    image: minio/mc:RELEASE.2025-05-21T01-59-54Z
    container_name: core_local_minio_bucket
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - ./.envs/.local/.django
    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set local http://minio:9000 \
          "$S3_ACCESS_KEY_ID" \
          "$S3_SECRET_ACCESS_KEY"

        mc mb --ignore-existing "local/$S3_BUCKET"
