# Generated by Django 6.0.4 on 2026-05-21 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('organizations', '0004_port_business_license_image_to_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID')),
                ('file', models.FileField(upload_to='imports/', verbose_name='Uploaded File')),
                ('module', models.CharField(max_length=50, verbose_name='Module')),
                ('errors', models.JSONField(blank=True, null=True, verbose_name='Errors')),
                ('progress', models.IntegerField(default=0, verbose_name='Progress')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
