# Generated by Django 6.0.4 on 2026-05-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_importjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Celery Task ID'),
        ),
    ]
