# Generated by Django 6.0.4 on 2026-05-15 23:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_gradesubject'),
        ('branches', '0001_initial'),
        ('organizations', '0002_organization_tin_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/attachments/', verbose_name='Attachment')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled At')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Is Urgent')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('SCHEDULED', 'Scheduled')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('target_roles', models.CharField(choices=[('PARENTS', 'Parents'), ('TEACHERS', 'Teachers'), ('BOTH', 'Both')], default='BOTH', max_length=20, verbose_name='Target Roles')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='branches.branch', verbose_name='Branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_grades', to='announcements.announcement', verbose_name='Announcement')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academics.grade', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Announcement Grade Target',
                'verbose_name_plural': 'Announcement Grade Targets',
                'unique_together': {('announcement', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='AnnouncementSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_sections', to='announcements.announcement', verbose_name='Announcement')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academics.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Announcement Section Target',
                'verbose_name_plural': 'Announcement Section Targets',
                'unique_together': {('announcement', 'section')},
            },
        ),
    ]
