# Generated by Django 6.0.4 on 2026-05-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-created_at'], 'verbose_name': 'Academic Year', 'verbose_name_plural': 'Academic Years'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['level'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-created_at'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
