# Generated by Django 6.0.4 on 2026-05-13 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicyear_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade', 'name', 'academic_year')},
        ),
    ]
