# Generated by Django 6.0.4 on 2026-05-13 23:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_section_unique_together_section_academic_year_and_more'),
        ('organizations', '0002_organization_tin_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='academics.grade', verbose_name='Grade')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='organizations.organization', verbose_name='Organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='academics.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Grade Subject',
                'verbose_name_plural': 'Grade Subjects',
                'ordering': ['grade__level', 'subject__name'],
                'unique_together': {('grade', 'subject')},
            },
        ),
    ]
