# Generated by Django 6.0.4 on 2026-05-16 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_parent_parentstudentlink_parent_profile'),
        ('teachers', '0002_homeroomassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('message_body', models.TextField(verbose_name='Message Body')),
                ('recipient_count', models.PositiveIntegerField(verbose_name='Recipient Count')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_logs', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Broadcast Log',
                'verbose_name_plural': 'Broadcast Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='students.parent', verbose_name='Parent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'unique_together': {('teacher', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.chatroom', verbose_name='Room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
