# Generated by Django 6.0.4 on 2026-05-12 00:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_academicyear_options_alter_grade_options_and_more'),
        ('branches', '0001_initial'),
        ('organizations', '0002_organization_tin_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('roll_no', models.CharField(max_length=50, verbose_name='Roll Number')),
                ('admission_date', models.DateField(verbose_name='Admission Date')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Photo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('WITHDRAWN', 'Withdrawn'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='branches.branch', verbose_name='Branch')),
                ('current_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.section', verbose_name='Current Section')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
                'unique_together': {('branch', 'roll_no')},
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('relationship_type', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], max_length=20, verbose_name='Relationship Type')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='Is Primary Contact')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL, verbose_name='Parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.student')),
            ],
            options={
                'verbose_name': 'Parent Student Link',
                'verbose_name_plural': 'Parent Student Links',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'parent')},
            },
        ),
    ]
