# Generated by Django 6.0.4 on 2026-05-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_section_unique_together_section_academic_year_and_more'),
        ('branches', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('branch', 'current_section', 'roll_no')},
        ),
    ]
