# Generated by Django 6.0.4 on 2026-05-20 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_gradesubject'),
        ('students', '0004_port_photo_to_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Admission Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.section', verbose_name='Current Section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Roll Number'),
        ),
    ]
