# Generated by Django 6.0.4 on 2026-05-14 02:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('organizations', '0002_organization_tin_number'),
        ('students', '0002_alter_student_unique_together'),
        ('teachers', '0002_homeroomassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('task_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('EXAM', 'Exam'), ('QUIZ', 'Quiz'), ('HOMEWORK', 'Homework'), ('PROJECT', 'Project'), ('LAB', 'Lab Work')], max_length=15, verbose_name='Task Type')),
                ('description', models.TextField(blank=True, verbose_name='Description / Instructions')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Total Marks')),
                ('passing_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. If set, results below this value trigger an Intervention Required log in the analytics app.', max_digits=6, null=True, verbose_name='Passing Marks')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='branches.branch', verbose_name='Branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='organizations.organization', verbose_name='Organization')),
                ('teacher_assignment', models.ForeignKey(help_text='Links this assessment to a specific Teacher, Subject, Section, and Academic Year — all derived from this single FK.', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='teachers.teachersubjectassignment', verbose_name='Teacher-Subject Assignment')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Obtained Marks')),
                ('submission_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('LATE', 'Late Submission'), ('MISSING', 'Missing'), ('GRADED', 'Graded')], default='PENDING', max_length=10, verbose_name='Submission Status')),
                ('feedback', models.TextField(blank=True, verbose_name='Teacher Feedback')),
                ('parent_confirmed', models.BooleanField(default=False, help_text='Set to True by the parent to confirm their child completed the homework. Relevant only when task_type=HOMEWORK.', verbose_name='Parent Confirmed Completion')),
                ('parent_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Parent Confirmed At')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment', verbose_name='Assessment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_results', to=settings.AUTH_USER_MODEL, verbose_name='Graded By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='organizations.organization', verbose_name='Organization')),
                ('parent_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_homework_results', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By Parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Assessment Result',
                'verbose_name_plural': 'Assessment Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['organization', 'task_type'], name='assessments_organiz_a62fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['teacher_assignment', 'status'], name='assessments_teacher_327c78_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['organization', 'submission_status'], name='assessments_organiz_07df12_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['student', 'assessment'], name='assessments_student_f9e390_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresult',
            unique_together={('assessment', 'student')},
        ),
    ]
