# Generated by Django 6.0.4 on 2026-05-30 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_calendardocument'),
        ('assessments', '0001_initial'),
        ('branches', '0001_initial'),
        ('organizations', '0004_port_business_license_image_to_media'),
        ('students', '0007_studentacademicyearsection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is Confirmed')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_confirmations', to='assessments.assessment', verbose_name='Assessment')),
                ('assessment_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework_confirmation', to='assessments.assessmentresult', verbose_name='Assessment Result')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_confirmations', to='branches.branch', verbose_name='Branch')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_confirmations', to='organizations.organization', verbose_name='Organization')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_confirmations', to='academics.section', verbose_name='Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_confirmations', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Homework Confirmation',
                'verbose_name_plural': 'Homework Confirmations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_confirmed'], name='assessments_organiz_901133_idx'), models.Index(fields=['branch', 'section'], name='assessments_branch__3a87e9_idx'), models.Index(fields=['assessment', 'student'], name='assessments_assessm_7480db_idx')],
            },
        ),
    ]
