# Generated by Django 6.0.4 on 2026-05-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_homeworkconfirmation'),
        ('students', '0007_studentacademicyearsection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeworkconfirmation',
            unique_together={('assessment', 'student')},
        ),
        migrations.RemoveField(
            model_name='homeworkconfirmation',
            name='assessment_result',
        ),
    ]
