# Generated by Django 6.0.4 on 2026-05-14 01:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_gradesubject'),
        ('branches', '0001_initial'),
        ('organizations', '0002_organization_tin_number'),
        ('students', '0002_alter_student_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('client_side_id', models.UUIDField(default=uuid.uuid4, help_text='UUID generated on the client for idempotent offline sync. If a record with this ID already exists, the server will return the existing record instead of creating a duplicate.', unique=True, verbose_name='Client-Side ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.academicyear', verbose_name='Academic Year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='branches.branch', verbose_name='Branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='organizations.organization', verbose_name='Organization')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.section', verbose_name='Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'section__name', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reason_category', models.CharField(choices=[('SICKNESS', 'Sickness'), ('TRANSPORTATION', 'Transportation Issue'), ('FAMILY_ISSUE', 'Family Issue'), ('EMERGENCY', 'Emergency'), ('RELIGIOUS', 'Religious Observance'), ('BEREAVEMENT', 'Bereavement'), ('UNKNOWN', 'Unknown'), ('OTHER', 'Other')], default='UNKNOWN', max_length=20, verbose_name='Reason Category')),
                ('note', models.TextField(blank=True, help_text='Free-text explanation from the parent.', verbose_name='Parent Note')),
                ('parent_confirmed', models.BooleanField(default=False, help_text='Set to True once the parent has acknowledged and explained the absence.', verbose_name='Parent Confirmed')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reason', to='attendance.attendance', verbose_name='Attendance Record')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_attendance_reasons', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reasons', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Attendance Reason',
                'verbose_name_plural': 'Attendance Reasons',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('total_present', models.PositiveIntegerField(default=0, verbose_name='Total Present')),
                ('total_absent', models.PositiveIntegerField(default=0, verbose_name='Total Absent')),
                ('total_late', models.PositiveIntegerField(default=0, verbose_name='Total Late')),
                ('total_excused', models.PositiveIntegerField(default=0, verbose_name='Total Excused')),
                ('total_school_days', models.PositiveIntegerField(default=0, verbose_name='Total School Days')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='academics.academicyear', verbose_name='Academic Year')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='organizations.organization', verbose_name='Organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'ordering': ['-academic_year__start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['organization', 'branch', 'date'], name='attendance__organiz_d616ba_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'academic_year'], name='attendance__student_8c9824_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['section', 'date'], name='attendance__section_7dbe4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('student', 'academic_year')},
        ),
    ]
