# Generated by Django 6.0.4 on 2026-05-13 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_section_unique_together_section_academic_year_and_more'),
        ('branches', '0001_initial'),
        ('organizations', '0002_organization_tin_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('specialization', models.CharField(blank=True, max_length=255, verbose_name='Specialization')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='branches.branch', verbose_name='Branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='organizations.organization', verbose_name='Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'unique_together': {('organization', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='TeacherQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('degree_name', models.CharField(max_length=255, verbose_name='Degree Name')),
                ('institution', models.CharField(max_length=255, verbose_name='Institution')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='Field of Study')),
                ('completion_date', models.DateField(verbose_name='Completion Date')),
                ('certificate_copy', models.FileField(blank=True, null=True, upload_to='teachers/certificates/', verbose_name='Certificate Copy')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_qualifications', to='organizations.organization', verbose_name='Organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Qualification',
                'verbose_name_plural': 'Teacher Qualifications',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.academicyear', verbose_name='Academic Year')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_assignments', to='organizations.organization', verbose_name='Organization')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.section', verbose_name='Section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Subject Assignment',
                'verbose_name_plural': 'Teacher Subject Assignments',
                'unique_together': {('teacher', 'subject', 'section', 'academic_year')},
            },
        ),
    ]
