# Generated by Django 6.0.4 on 2026-05-13 23:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_gradesubject'),
        ('branches', '0001_initial'),
        ('organizations', '0002_organization_tin_number'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeroomAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='academics.academicyear', verbose_name='Academic Year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='branches.branch', verbose_name='Branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='organizations.organization', verbose_name='Organization')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeroom_assignments', to='academics.section', verbose_name='Section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeroom_assignments', to='teachers.teacher', verbose_name='Homeroom Teacher')),
            ],
            options={
                'verbose_name': 'Homeroom Assignment',
                'verbose_name_plural': 'Homeroom Assignments',
                'ordering': ['-academic_year__start_date', 'section__name'],
                'unique_together': {('section', 'academic_year')},
            },
        ),
    ]
