# Generated by Django 6.0.4 on 2026-05-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchadmin',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='branchadmin',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='branchadmin',
            name='user',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='BranchAdmin',
        ),
    ]
