# Generated by Django 6.0.4 on 2026-05-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_branchadmin_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
