# Generated by Django 6.0.4 on 2026-05-14 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_tin_number'),
        ('students', '0002_alter_student_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('intervention_type', models.CharField(choices=[('LOW_GRADE', 'Low Grade'), ('ATTENDANCE', 'Attendance Concern'), ('BEHAVIOUR', 'Behaviour Concern'), ('OTHER', 'Other')], default='LOW_GRADE', max_length=20, verbose_name='Intervention Type')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10, verbose_name='Severity')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=15, verbose_name='Status')),
                ('source_model', models.CharField(blank=True, help_text="e.g. 'assessments.AssessmentResult'", max_length=100, verbose_name='Source Model')),
                ('source_id', models.UUIDField(blank=True, help_text='PK of the triggering record.', null=True, verbose_name='Source ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_logs', to='organizations.organization', verbose_name='Organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_logs', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Intervention Log',
                'verbose_name_plural': 'Intervention Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='analytics_i_organiz_4df0ad_idx'), models.Index(fields=['student', 'intervention_type'], name='analytics_i_student_f188f7_idx')],
            },
        ),
    ]
