# Generated by Django 6.0.4 on 2026-05-10 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text='Object storage key (must be globally unique)', max_length=1024, unique=True)),
                ('bucket', models.CharField(db_index=True, help_text='S3/MinIO bucket name', max_length=63)),
                ('file_name', models.CharField(help_text='Original file name (for display/download)', max_length=255)),
                ('content_type', models.CharField(help_text='MIME type (e.g., image/jpeg, application/pdf)', max_length=127)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes (set after upload confirmation)', null=True)),
                ('etag', models.CharField(blank=True, help_text='S3 ETag (set after upload confirmation)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='pending', help_text='Current upload lifecycle status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when upload was initiated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when upload status last changed')),
                ('uploaded_by', models.ForeignKey(help_text='User who initiated the upload', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='SHA256 hash of (user_id + file_name + content_type + time_window)', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this fingerprint was recorded')),
                ('media_file', models.OneToOneField(help_text='MediaFile created by this fingerprinted request', on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_record', to='media.mediafile')),
            ],
            options={
                'verbose_name': 'Upload Fingerprint',
                'verbose_name_plural': 'Upload Fingerprints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='media_media_uploade_e820ef_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['status', 'created_at'], name='media_media_status_00d779_idx'),
        ),
    ]
