# Generated by Django 6.0.4 on 2026-05-09 01:29

import django.db.models.deletion
import organizations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Trade Name')),
                ('license_no', models.CharField(blank=True, max_length=100, verbose_name='License Number')),
                ('client_full_name', models.CharField(max_length=255, verbose_name='Client Full Name')),
                ('business_address', models.TextField(verbose_name='Business Address')),
                ('business_phone_number', models.CharField(max_length=50, verbose_name='Business Phone Number')),
                ('client_phone_number', models.CharField(max_length=50, verbose_name='Client Phone Number')),
                ('business_license_image', models.ImageField(blank=True, null=True, upload_to=organizations.models.organization_license_upload_path, verbose_name='Business License Image')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], default='PENDING', max_length=20, verbose_name='Status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
