# Generated by Django 6.0.4 on 2026-05-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tin_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='TIN Number'),
        ),
    ]
