# Generated by Django 6.0.4 on 2026-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_tin_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="verification_checked_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Verification Checked At",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="verification_failure_reason",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Verification Failure Reason",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="verification_match_source",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Verification Match Source",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("verified", "Verified"),
                    ("pending_manual_review", "Pending Manual Review"),
                    ("verification_unavailable", "Verification Unavailable"),
                ],
                default="pending_manual_review",
                max_length=32,
                verbose_name="Verification Status",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="verified_license_no",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Verified License Number",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="verified_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Verified Name"),
        ),
        migrations.AddField(
            model_name="organization",
            name="verified_tin_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="Verified TIN Number"),
        ),
    ]
